# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Fan Pionier' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Masonry'
  pod 'SDWebImage'
  pod 'AFNetworking'
  pod 'UMCCommon'
  
  pod 'IQKeyboardManager'
  pod 'SCLAlertView-Objective-C'
  pod 'DZNEmptyDataSet'
  pod 'MJRefresh'
  pod	'BearSkill'
  
end
